# 阶段 1: 构建应用程序
FROM node:20 AS builder

WORKDIR /usr/src/app

# 复制 package 文件并安装依赖
COPY package*.json ./
RUN npm install -g pnpm bun
RUN pnpm install

# 复制源代码
COPY . .

# 构建应用程序
RUN bun run build

# 阶段 2: 创建生产镜像
FROM node:20

WORKDIR /usr/src/app

# 从构建器阶段复制 package 文件
COPY --from=builder /usr/src/app/package*.json ./

# 只安装生产依赖
RUN npm install -g pnpm bun
RUN pnpm install 

# 从构建器阶段复制编译后的应用程序和 drizzle 目录
COPY --from=builder /usr/src/app/dist ./dist
COPY --from=builder /usr/src/app/drizzle ./drizzle



# 暴露应用程序运行的端口
EXPOSE 3000

# 运行应用程序的命令
CMD [ "bun", "run", "start:prod" ]