# version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      # 生产环境端口
      - '8666:8666'
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5432/postgres
      - JWT_ACCESS_SECRET=your-access-secret-key-change-in-production
      - JWT_REFRESH_SECRET=your-refresh-secret-key-change-in-production
    depends_on:
      - postgres
    networks:
      - app-network
    command: >
      sh -c "bun run push && bun run dev"

  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: 'mydb'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
