FROM oven/bun AS base

FROM base AS builder
WORKDIR /app

# Install Python and build tools for native module compilation
# RUN apt-get update && apt-get install -y \
#     python3 \
#     python3-pip \
#     build-essential \
#     && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
COPY tsconfig.json ./
COPY src ./src

RUN bun install && \
    bun run docker:build:tsup

FROM base AS runner
WORKDIR /app

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 hono

COPY --from=builder --chown=hono:nodejs /app/node_modules /app/node_modules
COPY --from=builder --chown=hono:nodejs /app/dist /app/dist
COPY --from=builder --chown=hono:nodejs /app/package.json /app/package.json


USER hono
EXPOSE 3000

CMD ["bun", "run", "/app/dist/index.js"]